ARG python=python:3.9-alpine

FROM ${python} as build
WORKDIR /code

COPY requirements.txt .
RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev && \
    pip install --no-cache-dir --upgrade  -r requirements.txt


FROM ${python}
COPY --from=build /venv /venv

WORKDIR /code

ENV PATH=/venv/bin:$PATH
ENV DATABASE_USERNAME=postgres
ENV DATABASE_PASSWORD=postgres123
ENV DATABASE_NAME=ecommerce
ENV TEST_DATABASE_NAME=test_ecommerce
ENV DATABASE_HOST=TEST
ENV DATABASE_PORT=5432
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk --no-cache --update add libffi libressl postgresql-libs gcc libc-dev && adduser -D web

COPY . .

USER web

CMD ["pytest"]
