version: '3.9'

volumes:
  product_db:

networks:
  network:
    name: microservices
    external: true

services:

  product_service:
    container_name: ns-product-service
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8001:8000'
    depends_on:
      - product_db
    environment:
      DATABASE_HOST: product_db
      DATABASE_PORT: 5432

  product_db:
    image: postgres
    restart: always
    container_name: ns-product-db
    env_file:
      - .env  
    volumes:
      - product_db:/var/lib/postgresql/data
#      - ./config/postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
