version: '3'

volumes:
  product_test_db:

services:

  product_service:
    container_name: ns-product-service-test
    build:
      dockerfile: Dockerfile.test
      context: .
    depends_on:
      - product_db

  product_db:
    image: postgres
    restart: always
    container_name: ns-product-db-test
    env_file:
      - .env
    volumes:
      - product_test_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${TEST_DATABASE_NAME}
